[envs.default]
dependencies = [
  "coverage[toml]>=6.2",
  "freezegun",
  "mock",
  "pytest",
  "pytest-mock",
  "vcrpy",
]

[envs.lint]
detached = true
dependencies = [
  "black>=23.1.0",
  "mypy>=1.0.0",
  "ruff<0.0.262",
]
[envs.lint.scripts]
typing = "mypy --install-types --non-interactive {args:src tests}"
style = [
  "ruff {args:.}",
  "black --check --diff {args:.}",
]
fmt = [
  "black {args:.}",
  "ruff --fix {args:.}",
  "style",
]
all = [
  "style",
  "typing",
]
